name: Lint

on:
  pull_request:
    branches: [master]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      docs_only: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          predicate-quantifier: every
          filters: |
            docs:
              - 'skills/**'
              - 'docs/**'
              - 'contributing/**'
              - '*.md'
              - '.github/workflows/**' # TEMP: verify lint skip path on this PR

  lint:
    name: Format & Clippy
    needs: changes
    if: needs.changes.outputs.docs_only != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
        with:
          toolchain: "1.94.1"
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Install Linux system dependencies
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config

      - name: Check formatting
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --locked -- -D warnings
