name: TW doc review

on:
  pull_request:
    paths:
      - "README.md"
      - "docs/*.md"

permissions:
  contents: read

jobs:
  tw-review:
    uses: coralogix/documentation/.github/workflows/tw-doc-review.yml@master
    with:
      doc_paths: "README.md docs/*.md"
      shadow: true
    secrets: inherit
